import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Sidebar } from "~/components/navigation/sidebar";
import { cn } from "~/lib/utils";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "h-full w-full")}>
        <main className="max-w-6xl mx-auto flex items-center gap-20 py-20">
          <Sidebar />
          <div className="w-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
